### ISSUE TITLE
Startup fails: wait-for-db due to missing DB_PORT (undocumented)

### ISSUE THREAD

**Issue by matthanley** [solidnerd/docker-bookstack#7] opened 2016-09-26 10:23 UTC
Bookstack fails to start due to the missing and undocumented `DB_PORT` env variable in the latest build.

This was introduced in 7da6f70 due to not providing any default value for `DB_PORT`

**Comment by solidnerd** [comment] 2016-09-26 10:31
Hey, 
thanks for your report i will investigate this later. So far what I see is that a Default Port will be set at https://github.com/solidnerd/docker-bookstack/commit/7da6f704a05d8ce6010870a50875d7cef22540b3#diff-60713fb19f6c50a2473835df63ff17f9R16. Which version of mysql do use ?

**Comment by matthanley** [comment] 2016-09-26 10:49
I'm using Docker's `mariadb:latest`

The default you referenced only takes effect for the file `/var/www/BookStack/.env`, but the application never starts because at 7da6f704a05d8ce6010870a50875d7cef22540b3#diff-60713fb19f6c50a2473835df63ff17f9R85 `DB_PORT` is still unassigned.

**Comment by solidnerd** [comment] 2016-09-26 11:34
Okay I didn't get it first. The problem is the scope of the envs I will fix this later and refactor it to see that errors easier. Thanks for that 👍

**Comment by solidnerd** [comment] 2016-09-26 20:38
It should be fixed with #8 . Wait for the new latest version when it's build. If you have further problems with this reopen the issue.

**Closed as completed by solidnerd** 2016-09-26 20:38 UTC
